In [1]:
import numpy as np
a = np.ones((5, 1))
b = np.ones((1, 6))
c = np.ones((6,))
d = np.ones(())

In [2]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [3]:
a[:, np.newaxis, np.newaxis]

array([[[ 0.]],

       [[10.]],

       [[20.]],

       [[30.]]])

In [4]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation

In [5]:
# dist = sqrt(sum(diff**2,axis=-1))
codes[argmin(sqrt(sum(diff**2,axis=-1)))]

array([102., 203.])

In [6]:
x = np.arange(10)

In [7]:
x.shape = (2, 5)

In [8]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [9]:
z = np.arange(25).reshape((5, 5))
x = np.arange(4)
y = np.arange(4)
print(z[x[:, np.newaxis], y])
print(z[np.ix_(x, y)])
print(z)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
z[z.nonzero()] -= z[z.nonzero()]
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
x[rowsum <= 2]

array([[0, 1],
       [1, 1]])

In [12]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
x[x % 2 == 0]
x[rows]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [13]:
columns = [0, 2]
rows.dtype = np.int32
rows

array([16777472], dtype=int32)

In [ ]:
x = np.arange(30).reshape(2, 3, 5)
b = np.array([[True, True, True], [True, True, True]])
x[b]

array([ 0,  2,  4,  5,  7,  9, 10, 12, 14, 15, 17, 19, 20, 22, 24, 25, 27,
       29])

In [52]:
y = np.arange(8).reshape(2, 2, 2)
index = np.ones((2, 5, 2), dtype=np.int64)
print(y[index])


[[[[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]]



 [[[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]


  [[[4 5]
    [6 7]]

   [[4 5]
    [6 7]]]]]


In [67]:
x = np.arange(35).reshape(5, 7)
b = x > 20
print(b[:, 5])
x[b[:, 5]]


[False False False  True  True]


array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [84]:
x = np.array([1, 2])
x[...]

array([1, 2])